# Generated by Django 5.0 on 2024-01-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='available',
            field=models.IntegerField(default=10),
        ),
    ]
